-- test, jsp, ....
--CREATE USER jsp IDENTIFIED BY 123456 DEFAULT TABLESPACE USERS;
--
--GRANT CONNECT, RESOURCE TO jsp;
--
--ALTER USER jsp DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

--관리자 계정 ora_user 으로 사용자 2번 jsp 계정생성
--사용자 2번 jsp 계정
--아이디 jsp / 비번 123456
-- EMPLOYEES 테이블 생성
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE,
    JOB_ID VARCHAR2(50),
    SALARY NUMBER,
    MANAGER_ID NUMBER,
    DEPARTMENT_ID NUMBER
);

--EMPLOYEES 테이블 수정
ALTER TABLE EMPLOYEES ADD USER_PW VARCHAR2(25CHAR) DEFAULT '1234';
COMMIT;

--EMPLOYEES 테이블 삭제
DROP TABLE EMPLOYEES;

--EMPLOYEES 테이블 조회
SELECT * FROM EMPLOYEES;
SELECT COUNT(*) CNT FROM EMPLOYEES WHERE EMPLOYEE_ID = 1 AND USER_PW='1234';
SELECT EMPLOYEE_ID, USER_PW FROM EMPLOYEES WHERE EMPLOYEE_ID = 1;

SELECT count(*) FROM EMPLOYEES;
SELECT * FROM EMPLOYEES;
INSERT INTO EMPLOYEES VALUES(1);

INSERT INTO EMPLOYEES VALUES (1, 'John', 'Doe', 'john.doe@example.com', '123-456-7890', TO_DATE('2022-01-01', 'YYYY-MM-DD'), 'MANAGER', 50000, NULL, 10);
INSERT INTO EMPLOYEES VALUES (2, 'Jane', 'Smith', 'jane.smith@example.com', '987-654-3210', TO_DATE('2022-02-01', 'YYYY-MM-DD'), 'CLERK', 30000, 1, 20);
INSERT INTO EMPLOYEES VALUES (3, 'Bob', 'Johnson', 'bob.johnson@example.com', '555-123-4567', TO_DATE('2022-03-01', 'YYYY-MM-DD'), 'ANALYST', 60000, 1, 30);

-- EMPLOYEE_ID가 2인 직원의 정보를 수정
UPDATE EMPLOYEES
SET FIRST_NAME = 'UpdatedFirstName',
    LAST_NAME = 'UpdatedLastName',
    EMAIL = 'updated.email@example.com',
    PHONE_NUMBER = '999-999-9999',
    HIRE_DATE = TO_DATE('2022-04-01', 'YYYY-MM-DD'),
    JOB_ID = 'UPDATED_JOB',
    SALARY = 40000,
    MANAGER_ID = 1,
    DEPARTMENT_ID = 20
WHERE EMPLOYEE_ID = 2;

-- EMPLOYEE_ID가 2인 직원을 삭제
DELETE FROM EMPLOYEES
WHERE EMPLOYEE_ID = 2;

commit;
CREATE TABLE DEPARTMENTS(
    DEPART_ID NUMBER,
    DEPART_NAME VARCHAR2(10char)
);

SELECT * FROM DEPARTMENTS;
DELETE FROM DEPARTMENTS;



--게시판 시퀀스
CREATE SEQUENCE BO_FREE_SEQ
   START WITH 1
   INCREMENT BY 1
   NOMAXVALUE
   NOCYCLE;

--게시판 테이블
CREATE TABLE BO_FREE (
    num NUMBER DEFAULT BO_FREE_SEQ.NEXTVAL PRIMARY KEY,
    id VARCHAR2(15),
    pw VARCHAR2(15),
    name VARCHAR2(10) NOT NULL,
    hp VARCHAR2(20),
    email VARCHAR2(80),
    hompy VARCHAR2(100),
    subject VARCHAR2(255) NOT NULL,
    content CLOB NOT NULL,
    hit NUMBER DEFAULT 0,
    regdate DATE DEFAULT SYSDATE
);
--게시판 샘플
INSERT INTO BO_FREE (id, pw, name, hp, email, hompy, subject, content)
VALUES ('user123', 'password123', 'John Doe', '010-1234-5678', 'john@example.com', 'http://john.example.com', '게시글 제목', '게시글 내용입니다.');

COMMIT;
SELECT NUM, SUBJECT, NAME, REGDATE,CONTENT FROM BO_FREE WHERE NUM=1;

