/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-07 06:16:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import utils.DBConfig;
import java.sql.*;
import java.util.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1709707807062L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1709707807070L));
    _jspx_dependants.put("/login_header.jsp", Long.valueOf(1709707807068L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utils.DBConfig");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.time.LocalDate");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- 차트.js 라이브러리 -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("<script defer type=\"text/javascript\" src=\"js/chart.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/index.css\">\r\n");
      out.write("<link rel=\"icon\" href=\"./image/favicon.ico\" />\r\n");
      out.write("<link >\r\n");
      out.write("<title>의류 생산 관리 시스템</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

    // 로그인 여부 확인
    if (session.getAttribute("id") == null) {
        response.sendRedirect("index.jsp"); // 로그인 페이지로 이동
    }

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("			<a href=\"main.jsp\" class=\"logodiv\">\r\n");
      out.write("				<img src=\"image/icons.png\" alt=\"icon\">\r\n");
      out.write("				<div class=\"logoname\">의류 생산 관리</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/menu.css\">\r\n");
      out.write("<link rel=\"icon\" href=\"./image/favicon.ico\" />\r\n");
      out.write("<!-- 메뉴 아이콘 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("<title>의류 생산 관리 시스템</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"round\">\r\n");
      out.write("		<div id=\"menu\">\r\n");
      out.write("        <input type=\"checkbox\" id=\"menubtn\">\r\n");
      out.write("        <label for=\"menubtn\" id=\"menubtnlabel\"><span class=\"material-symbols-outlined\">menu</span></label>\r\n");
      out.write("        <ul id=\"menuUl\">\r\n");
      out.write("            <li><a href=\"orderList.jsp\" class=\"dir\"><span class=\"material-symbols-outlined dir2\">menu_book</span> 주문 의뢰서</a></li>\r\n");
      out.write("            <li><a href=\"store.jsp\" class=\"dir\"><span class=\"material-symbols-outlined dir2\">inventory_2</span> 입고 등록</a></li>\r\n");
      out.write("            <li><a href=\"inventory.jsp\" class=\"dir\"><span class=\"material-symbols-outlined dir2\">inventory_2</span> 재고 관리</a></li>\r\n");
      out.write("            <li><a href=\"product_list.jsp\" class=\"dir\"><span class=\"material-symbols-outlined dir2\">inventory_2</span> 제품 관리</a></li>\r\n");
      out.write("            <li><a href=\"nike/button.html\" class=\"dir\"><span class=\"material-symbols-outlined dir2\">inventory_2</span> 월별 매출 관리</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		<ul class=\"menu\">\r\n");
      out.write("			<li class=\"list\">\r\n");
      out.write("			<a>");
      out.print(session.getAttribute("id"));
      out.write("님, 환영합니다.</a>\r\n");
      out.write("			<ul class=\"submenu\">\r\n");
      out.write("				<li class=\"list\"><a href=\"manageredit.jsp\">회원정보</a></li>\r\n");
      out.write("				<li class=\"list\"><a href=\"logout.jsp\">로그아웃</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	 <div id=\"container\">\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("            <div id=\"lineChart\">\r\n");
      out.write("            ");

            LocalDate now = LocalDate.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy");
            String formnow = now.format(formatter);
            
            
            String year = request.getParameter("year");
            if(year==null){
            	year=formnow;
            }
            Connection conn = null;
    		PreparedStatement pstmt = null; 
    		ResultSet rs = null;
    		
    		int totalSales = 0;
            
      out.write("\r\n");
      out.write("                <div class=\"title\">\r\n");
      out.write("                	<select name=\"\" id=\"years\" onchange=\"yearChange()\">\r\n");
      out.write("                ");

        		try{
        			conn=DBConfig.getConnection();
        			
        			String sql = "SELECT TO_CHAR(MIN(IMPORT_DATE),'YYYY'), TO_CHAR(SYSDATE,'YYYY')  FROM IMPORT i";
       				pstmt = conn.prepareStatement(sql);
       				rs=pstmt.executeQuery();
       				
       				int minYear =0;
       				int maxYear =0;
       				
       				if(rs.next()){
       					minYear = Integer.parseInt(rs.getString(1));
       					maxYear = Integer.parseInt(rs.getString(2));
       				}
       					while(minYear<=maxYear){
       							if(Integer.parseInt(year)==minYear){
   									
      out.write("\r\n");
      out.write("               						<option value=\"");
      out.print(minYear);
      out.write("\" selected>");
      out.print(minYear);
      out.write("</option>\r\n");
      out.write("               						");

   								} else{
   									
      out.write("\r\n");
      out.write("               						<option value=\"");
      out.print(minYear);
      out.write('"');
      out.write('>');
      out.print(minYear);
      out.write("</option>\r\n");
      out.write("               						");

   								}
       						minYear++;
       					}
       			
      out.write("\r\n");
      out.write("       				</select>\r\n");
      out.write("       			\r\n");
      out.write("       				");

       				sql = "SELECT SUBSTR(EXDATE,6,8) SEARCHDATE, SUM(SALES) "+
       						"FROM "+
       						"(SELECT E.ITEM_NUM, TO_CHAR(EXPORT_DATE,'YYYY-MM') EXDATE,SUM(EXPORT_QUANTITY*PRICE)-SUM(EXPORT_QUANTITY *A.VAT) sales "+
       						"FROM EXPORT e, (SELECT ITEM_NUM, SUPPLY_PRICE+VAT VAT FROM IMPORT i GROUP BY ITEM_NUM,(SUPPLY_PRICE+VAT))A "+
       						"WHERE TO_CHAR(e.EXPORT_DATE,'YYYY')='"+year+"' AND E.ITEM_NUM =A.ITEM_NUM "+
       						"GROUP BY E.ITEM_NUM,TO_CHAR(EXPORT_DATE,'YYYY-MM')) "+
       						"GROUP BY EXDATE "+
       						"ORDER BY SEARCHDATE ";
       				pstmt = conn.prepareStatement(sql);
       				rs=pstmt.executeQuery();
       				int month=0;
       				int array[]=new int[12];
       				
       				
       				System.out.println();
       				while(rs.next()){
       					month=Integer.parseInt(rs.getString(1));
       					for(int i=1;i<=12;i++){
       						if(i==month){
       							array[i-1]=month;
       							totalSales+=rs.getInt(2);
       							
      out.write("\r\n");
      out.write("       							<input type=\"hidden\" id=\"month");
      out.print(i);
      out.write("\" value=\"");
      out.print(rs.getInt(2));
      out.write("\">\r\n");
      out.write("       							");

       						}
       					}
       				}
       				
       				for(int i=1;i<=12;i++){
       					if(array[i-1]!=i){
       						
      out.write("\r\n");
      out.write("								<input type=\"hidden\" id=\"month");
      out.print(i);
      out.write("\" value=\"0\">\r\n");
      out.write("							");

       					}
       				}
        		}catch(Exception e){
        			
        		}
                
      out.write("\r\n");
      out.write("                <div id=\"total\">총 ");
      out.print(String.format("%,d",totalSales));
      out.write("원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <canvas id=\"myChart\" width=\"1000px\" height=\"600px\"></canvas>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <footer>\r\n");
      out.write("  	<div>\r\n");
      out.write("			<div>이용약관 ·운영정책 ·청소년보호정책 ·위치정보이용약관 ·개인정보처리방침 ·웹접근성안내 ·고객센터</div>\r\n");
      out.write("			<div>Copyright &#169; SM Corp. All rights reserved.<span><img src=\"./image/logo.png\" alt=\"logo\"></span></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        const ctx = document.getElementById('myChart');\r\n");
      out.write("        var opt = document.getElementById(\"years\");\r\n");
      out.write("        var optVal = opt.options[opt.selectedIndex].value;\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        function yearChange() {\r\n");
      out.write("        	var optVal = opt.options[opt.selectedIndex].value;\r\n");
      out.write("            location.href='main.jsp?year='+optVal;\r\n");
      out.write("		}\r\n");
      out.write("        \r\n");
      out.write("        var jan = document.getElementById(\"month1\").value;\r\n");
      out.write("        var feb = document.getElementById(\"month2\").value;\r\n");
      out.write("        var mar = document.getElementById(\"month3\").value;\r\n");
      out.write("        var apr = document.getElementById(\"month4\").value;\r\n");
      out.write("        var may = document.getElementById(\"month5\").value;\r\n");
      out.write("        var jun = document.getElementById(\"month6\").value;\r\n");
      out.write("        var jul = document.getElementById(\"month7\").value;\r\n");
      out.write("        var aug = document.getElementById(\"month8\").value;\r\n");
      out.write("        var sep = document.getElementById(\"month9\").value;\r\n");
      out.write("        var oct = document.getElementById(\"month10\").value;\r\n");
      out.write("        var nov = document.getElementById(\"month11\").value;\r\n");
      out.write("        var dec = document.getElementById(\"month12\").value;\r\n");
      out.write("        \r\n");
      out.write("        new Chart(ctx, {\r\n");
      out.write("          type: 'line',\r\n");
      out.write("          data: {\r\n");
      out.write("            labels: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],\r\n");
      out.write("            datasets: [{\r\n");
      out.write("              label: optVal,\r\n");
      out.write("              data: [jan, feb, mar, apr, may, jun,jul,aug,sep,oct,nov,dec],\r\n");
      out.write("              borderWidth: 1,\r\n");
      out.write("              borderColor: 'red',\r\n");
      out.write("              backgroundColor:'#9BD0F5',\r\n");
      out.write("              fill:{\r\n");
      out.write("            	  target:'origin'\r\n");
      out.write("              }\r\n");
      out.write("            }]\r\n");
      out.write("          },\r\n");
      out.write("          options: {\r\n");
      out.write("            responsive:true,\r\n");
      out.write("            plugins: {\r\n");
      out.write("              title: {\r\n");
      out.write("                  display: true,\r\n");
      out.write("                  text: '순매출 수익',\r\n");
      out.write("                  font:{\r\n");
      out.write("                    size:30,\r\n");
      out.write("                    family:'TTHakgyoansimMoheomgaB'\r\n");
      out.write("                  }\r\n");
      out.write("              }\r\n");
      out.write("            },\r\n");
      out.write("            scales:{\r\n");
      out.write("            	x:{\r\n");
      out.write("            		display:true,\r\n");
      out.write("            		title:{\r\n");
      out.write("            			display:true,\r\n");
      out.write("            			text:'매월',\r\n");
      out.write("            			font:{\r\n");
      out.write("            				size:20,\r\n");
      out.write("            				family:'TTHakgyoansimMoheomgaB'\r\n");
      out.write("            			}\r\n");
      out.write("            		},\r\n");
      out.write("            	},\r\n");
      out.write("            	y:{\r\n");
      out.write("            		display:true,\r\n");
      out.write("            		title:{\r\n");
      out.write("            			display:true,\r\n");
      out.write("            			text:'매출수익',\r\n");
      out.write("            			font:{\r\n");
      out.write("            				size:20,\r\n");
      out.write("            				family:'TTHakgyoansimMoheomgaB'\r\n");
      out.write("            			}\r\n");
      out.write("            		},\r\n");
      out.write("            	}\r\n");
      out.write("            },\r\n");
      out.write("            transitions:{\r\n");
      out.write("            	show:{\r\n");
      out.write("            		animations:{\r\n");
      out.write("            			x:{\r\n");
      out.write("            				from:0\r\n");
      out.write("            			}\r\n");
      out.write("            		}\r\n");
      out.write("            	},\r\n");
      out.write("            	hide:{\r\n");
      out.write("            		animations:{\r\n");
      out.write("            			x:{\r\n");
      out.write("            				to:0\r\n");
      out.write("            			}\r\n");
      out.write("            		}\r\n");
      out.write("            	}\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        });   \r\n");
      out.write("      </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
