/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-07 06:16:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import utils.DBConfig;
import java.sql.*;
import java.util.*;

public final class store_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1709707807062L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1709707807070L));
    _jspx_dependants.put("/login_header.jsp", Long.valueOf(1709707807068L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utils.DBConfig");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/store.css\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./image/favicon.ico\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("    <title>의류 생산 시스템:입고</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');

    // 로그인 여부 확인
    if (session.getAttribute("id") == null) {
        response.sendRedirect("index.jsp"); // 로그인 페이지로 이동
    }

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("			<a href=\"main.jsp\" class=\"logodiv\">\r\n");
      out.write("				<img src=\"image/icons.png\" alt=\"icon\">\r\n");
      out.write("				<div class=\"logoname\">의류 생산 관리</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/menu.css\">\r\n");
      out.write("<link rel=\"icon\" href=\"./image/favicon.ico\" />\r\n");
      out.write("<!-- 메뉴 아이콘 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("<title>의류 생산 관리 시스템</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"round\">\r\n");
      out.write("		<div id=\"menu\">\r\n");
      out.write("        <input type=\"checkbox\" id=\"menubtn\">\r\n");
      out.write("        <label for=\"menubtn\" id=\"menubtnlabel\"><span class=\"material-symbols-outlined\">menu</span></label>\r\n");
      out.write("        <ul id=\"menuUl\">\r\n");
      out.write("            <li><a href=\"orderList.jsp\" class=\"dir\"><span class=\"material-symbols-outlined dir2\">menu_book</span> 주문 의뢰서</a></li>\r\n");
      out.write("            <li><a href=\"store.jsp\" class=\"dir\"><span class=\"material-symbols-outlined dir2\">inventory_2</span> 입고 등록</a></li>\r\n");
      out.write("            <li><a href=\"inventory.jsp\" class=\"dir\"><span class=\"material-symbols-outlined dir2\">inventory_2</span> 재고 관리</a></li>\r\n");
      out.write("            <li><a href=\"product_list.jsp\" class=\"dir\"><span class=\"material-symbols-outlined dir2\">inventory_2</span> 제품 관리</a></li>\r\n");
      out.write("            <li><a href=\"nike/button.html\" class=\"dir\"><span class=\"material-symbols-outlined dir2\">inventory_2</span> 월별 매출 관리</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		<ul class=\"menu\">\r\n");
      out.write("			<li class=\"list\">\r\n");
      out.write("			<a>");
      out.print(session.getAttribute("id"));
      out.write("님, 환영합니다.</a>\r\n");
      out.write("			<ul class=\"submenu\">\r\n");
      out.write("				<li class=\"list\"><a href=\"manageredit.jsp\">회원정보</a></li>\r\n");
      out.write("				<li class=\"list\"><a href=\"logout.jsp\">로그아웃</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <div id=\"info\">\r\n");
      out.write("                <div id=\"title\">\r\n");
      out.write("                    <span>입출고 등록</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");

                Connection conn = null;
				PreparedStatement pstmt = null;
				ResultSet rs = null;
                
                String type = request.getParameter("selecttype");
                String num = request.getParameter("num");
                String itemSearch = request.getParameter("itemSearch");
                
                if(num==null){
                	num="0";
                }
                
                if(type==null){
                	type="item";
                }
                if(itemSearch==null){
                	itemSearch="";
                }
				
				try{
					conn=DBConfig.getConnection();
					
                
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <form action=\"storeInsert.jsp\" id=\"formInsert\" method=\"get\" onsubmit=\"return false\">\r\n");
      out.write("                	<input type=\"hidden\" name=\"type\" value=\"");
      out.print(type);
      out.write("\">\r\n");
      out.write("                    <ul class=\"subject\">\r\n");
      out.write("                    	");

                    		if(type.equals("item")){
                    			
      out.write("\r\n");
      out.write("                    			<li class=\"line\">\r\n");
      out.write("			                        <div class=\"lab\">구분</div>\r\n");
      out.write("			                        <label for=\"import\" class=\"choice\">입고</label>\r\n");
      out.write("			                        <input type=\"radio\" id=\"import\" name=\"info\" value=\"import\" checked>\r\n");
      out.write("			                        <label for=\"import\" class=\"choice\">출고</label>\r\n");
      out.write("			                        <input type=\"radio\" id=\"export\" name=\"info\" value=\"export\">\r\n");
      out.write("		                        </li>\r\n");
      out.write("                    			");

                    		}
                    	
      out.write("\r\n");
      out.write("                        <li class=\"line\">\r\n");
      out.write("	                        <div class=\"lab\">입고일</div>\r\n");
      out.write("	                        <input type=\"text\" name=\"date\" class=\"text\" id=\"item_date\" placeholder=\"날짜 입력\">\r\n");
      out.write("	                        <input type=\"date\" id=\"date\" onchange=\"dateMethod()\">\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"line\">\r\n");
      out.write("	                        <div class=\"lab\">수량</div>\r\n");
      out.write("	                        <input type=\"text\" name=\"itemcount\" class=\"text\" id=\"quantity\" placeholder=\"수량 입력\">\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"line\">\r\n");
      out.write("	                        <div class=\"lab\">제품 번호</div>\r\n");
      out.write("	                        <input type=\"hidden\" name=\"itemnum\" class=\"text\" id=\"item_num\" placeholder=\"제품 번호 입력\">\r\n");
      out.write("	                        <div id=\"item_num2\" class=\"subjectbox\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"line\">\r\n");
      out.write("	                        <div class=\"lab\">제품명</div>\r\n");
      out.write("	                        <input type=\"hidden\" name=\"itemname\" class=\"text\" id=\"item_name\" placeholder=\"제품명 입력\">\r\n");
      out.write("	                        <div id=\"item_name2\" class=\"subjectbox\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"line\">\r\n");
      out.write("	                        <div class=\"lab\">사이즈</div>\r\n");
      out.write("	                        <input type=\"hidden\" name=\"itemsize\" class=\"text\" id=\"item_size\" placeholder=\"사이즈 입력\">\r\n");
      out.write("	                        <div id=\"item_size2\" class=\"subjectbox\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div id=\"ok\">\r\n");
      out.write("                        <input type=\"submit\" value=\"입력\" id=\"sub\" onclick=\"checkTest()\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            ");

	          	//페이징 처리
	            String currentPage=request.getParameter("pagenum");
				int totalCount=0;
				int pageCount=5;
				int limit=10;
				int totalPage=0;
				int pageGroup=0;
				int firstNumber=0;
				int lastNumber=0;
				int row = 0;
				int lastpageGroup=0;
				int next=0;
				int prev=0;
            
	            if(currentPage==null){
	    			currentPage="1";
	    		}
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"search\">\r\n");
      out.write("                <div class=\"searchText\">\r\n");
      out.write("                	<select name=\"\" id=\"searchselect\" onchange=\"selectType()\">\r\n");
      out.write("                	");
 
                		if(type.equals("item")){
                			
      out.write("\r\n");
      out.write("                        	<option value=\"item\" selected>제품</option>\r\n");
      out.write("                        	<option value=\"order\">주문 의뢰서</option>\r\n");
      out.write("                			");

                		}else if(type.equals("order")){
                			
      out.write("\r\n");
      out.write("                        	<option value=\"item\">제품</option>\r\n");
      out.write("                        	<option value=\"order\" selected>주문 의뢰서</option>\r\n");
      out.write("                			");

                		}else{
                			
      out.write("\r\n");
      out.write("                        	<option value=\"item\">제품</option>\r\n");
      out.write("                        	<option value=\"order\">주문 의뢰서</option>\r\n");
      out.write("                			");

                		}
                		
                		
                	
      out.write("\r\n");
      out.write("                	</select>\r\n");
      out.write("                    <input type=\"text\" name=\"itemNameSearch\" id=\"itemSearchId\" class=\"text\" placeholder=\"제품명 입력\" value=\"");
      out.print(itemSearch);
      out.write("\">\r\n");
      out.write("                    <button id=\"searchbtn\" onclick=\"itemSearch()\">검색</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"result\">\r\n");
      out.write("                    <div id=\"resultTable\">\r\n");
      out.write("                        <table id=\"tableSelect\">\r\n");
      out.write("                            <tr class=\"resultCulum\">\r\n");
      out.write("                               ");

                               		if(type.equals("item")){
                               			String sql2 = "SELECT count(*) FROM products  WHERE ITEM_NAME LIKE '%"+itemSearch+"%'";
                            			pstmt = conn.prepareStatement(sql2);
                            			rs = pstmt.executeQuery();
                            			if(rs.next()){
                            				totalCount+=rs.getInt(1);
                            			}
                               			
      out.write("\r\n");
      out.write("                               				<th class=\"resultRow resultTitle radio\">선택</th>\r\n");
      out.write("		                                	<th class=\"resultRow resultTitle type\">종류</th>\r\n");
      out.write("		                                	<th class=\"resultRow resultTitle name\">제품명</th>\r\n");
      out.write("		                                	<th class=\"resultRow resultTitle size\">사이즈</th>\r\n");
      out.write("                               			");

                               		}else if(type.equals("order")){
                               			String sql = "SELECT count(*) FROM order_product  WHERE ITEM_NAME LIKE '%"+itemSearch+"%'";
                            			pstmt = conn.prepareStatement(sql);
                            			rs = pstmt.executeQuery();
                            			if(rs.next()){
                            				totalCount+=rs.getInt(1);
                            			}
                               			
      out.write("\r\n");
      out.write("                               				<th class=\"resultRow resultTitle radio\">선택</th>\r\n");
      out.write("                                			<th class=\"resultRow resultTitle type\">종류</th>\r\n");
      out.write("                                			<th class=\"resultRow resultTitle name\">제품명</th>\r\n");
      out.write("                                			<th class=\"resultRow resultTitle size\">사이즈</th>\r\n");
      out.write("                                			<th class=\"resultRow resultTitle\">수량</th>\r\n");
      out.write("                               			");

                               		}
                               
      out.write("\r\n");
      out.write("                               ");

                               totalPage = (int)(totalCount/limit);
	                       		if(totalCount%limit>0){
	                       			totalPage+=1;
	                       		}
	                       		
	                       		if(totalPage<Integer.parseInt(currentPage)){
	                       			currentPage=Integer.toString(totalPage);
	                       		}
	                       		
	                       		pageGroup=Integer.valueOf(currentPage)/pageCount;
	                       		lastpageGroup=totalPage/pageCount;
	                       		
	                       		if(pageGroup==0){
	                       			pageGroup++;
	                       		}
	                       		
	                       		if(lastpageGroup==0){
	                       			lastpageGroup++;
	                       		}
	                       		
	                       		lastNumber = pageGroup*pageCount;
	                       		if(lastNumber>totalPage){
	                       			lastNumber=totalPage;
	                       		}
	                       		
	                       		firstNumber = lastNumber-(pageCount-1);
	                       		
	                       		next = lastNumber+1;
	                       		prev = firstNumber-1;
	                       		
	                       		if(firstNumber<=0){
	                       			firstNumber=1;
	                       			prev=1;
	                       		}
	                       		
	                       		int count = Integer.parseInt(currentPage)-1;
	                       		row = limit*count;
                               
      out.write("\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            ");

									if(type.equals("item")){
										String sql = "SELECT item_num, item_type, item_name, item_size  FROM products  WHERE ITEM_NAME LIKE '%"+itemSearch+"%' order by item_num OFFSET "+row+" ROWS FETCH NEXT "+limit+" ROWS ONLY";
										pstmt = conn.prepareStatement(sql);
										
										rs = pstmt.executeQuery();

										while(rs.next()){

											
      out.write("\r\n");
      out.write("												<tr class=\"resultCulumn\">\r\n");
      out.write("					                                <td class=\"resultRow selectRow\">");
      out.print(rs.getString(1) );
      out.write("</td>\r\n");
      out.write("					                                <td class=\"resultRow selectRow\">");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("					                                <td class=\"resultRow selectRow\">");
      out.print(rs.getString(3) );
      out.write("</td>\r\n");
      out.write("					                                <td class=\"resultRow selectRow\">");
      out.print(rs.getString(4) );
      out.write("</td>\r\n");
      out.write("					                            </tr>\r\n");
      out.write("											");

										}
									} else if(type.equals("order")){
										String sql2 = "SELECT order_num, item_type, item_name, item_size,quantity FROM order_product  WHERE ITEM_NAME LIKE '%"+itemSearch+"%' order by ORDER_NUM OFFSET "+row+" ROWS FETCH NEXT "+limit+" ROWS ONLY";
										pstmt = conn.prepareStatement(sql2);
										
										rs = pstmt.executeQuery();

										while(rs.next()){

											
      out.write("\r\n");
      out.write("												<tr class=\"resultCulumn\">\r\n");
      out.write("					                                <td class=\"resultRow selectRow\">");
      out.print(rs.getString(1) );
      out.write("</td>\r\n");
      out.write("					                                <td class=\"resultRow selectRow\">");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("					                                <td class=\"resultRow selectRow\">");
      out.print(rs.getString(3) );
      out.write("</td>\r\n");
      out.write("					                                <td class=\"resultRow selectRow\">");
      out.print(rs.getString(4) );
      out.write("</td>\r\n");
      out.write("					                                <td class=\"resultRow selectRow\">");
      out.print(rs.getString(5) );
      out.write("</td>\r\n");
      out.write("					                            </tr>\r\n");
      out.write("											");

										}
									}
									
								
        					
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"page\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            ");

                            	if(pageGroup!=1){
                            		
      out.write("\r\n");
      out.write("                            		<li><a class=\"pageNum pagebtn\" href=\"store.jsp?selecttype=");
      out.print(type);
      out.write("&itemSearch=");
      out.print(itemSearch);
      out.write("&pagenum=");
      out.print(prev);
      out.write("\">이전</a></li>\r\n");
      out.write("                            		");

                            	}
                            
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                            ");

                            	for(int i=firstNumber;i<=lastNumber;i++){
                            		if (i == Integer.parseInt(currentPage)) { 
                            		
      out.write("\r\n");
      out.write("                            		<li>\r\n");
      out.write("                            			<a class=\"pageNum\" href=\"store.jsp?selecttype=");
      out.print(type);
      out.write("&itemSearch=");
      out.print(itemSearch);
      out.write("&pagenum=");
      out.print(i);
      out.write("\" style=\"background-color: #40A2D8\">");
      out.print(i);
      out.write("</a>\r\n");
      out.write("                            		</li>\r\n");
      out.write("                            		");

                            		} else{
                            			
      out.write("\r\n");
      out.write("                                		<li>\r\n");
      out.write("                                			<a class=\"pageNum\" href=\"store.jsp?selecttype=");
      out.print(type);
      out.write("&itemSearch=");
      out.print(itemSearch);
      out.write("&pagenum=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("                                		</li>\r\n");
      out.write("                                		");

                            		}
                            	}
                            
      out.write("\r\n");
      out.write("                            ");

                            	if(pageGroup!=lastpageGroup && pageGroup !=1){
                            		
      out.write("\r\n");
      out.write("                            			<li><a class=\"pageNum pagebtn\" href=\"store.jsp?selecttype=");
      out.print(type);
      out.write("&itemSearch=");
      out.print(itemSearch);
      out.write("&pagenum=");
      out.print(next);
      out.write("\">다음</a></li>\r\n");
      out.write("                            		");

                            	}
                            
      out.write(" \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

						}catch(SQLException e){
							System.out.println("에러 로그:"+e.getMessage());
						}
                    
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <footer>\r\n");
      out.write("  	<div>\r\n");
      out.write("			<div>이용약관 ·운영정책 ·청소년보호정책 ·위치정보이용약관 ·개인정보처리방침 ·웹접근성안내 ·고객센터</div>\r\n");
      out.write("			<div>Copyright &#169; SM Corp. All rights reserved.<span><img src=\"./image/logo.png\" alt=\"logo\"></span></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    	function selectType(){\r\n");
      out.write("    		var opt = document.getElementById(\"searchselect\");\r\n");
      out.write("            var optVal = opt.options[opt.selectedIndex].value;\r\n");
      out.write("            location.href='store.jsp?selecttype='+optVal;\r\n");
      out.write("    	}\r\n");
      out.write("    \r\n");
      out.write("    	function dateMethod() {\r\n");
      out.write("			var dateControl = document.querySelector('input[type=\"date\"]').value;\r\n");
      out.write("			var itemDate = document.getElementById(\"item_date\").value=dateControl;\r\n");
      out.write("		}\r\n");
      out.write("    	\r\n");
      out.write("    	function itemSearch() {\r\n");
      out.write("			var itemSearchId = document.getElementById(\"itemSearchId\").value;\r\n");
      out.write("			var opt = document.getElementById(\"searchselect\");\r\n");
      out.write("            var optVal = opt.options[opt.selectedIndex].value;\r\n");
      out.write("            \r\n");
      out.write("			location.href='store.jsp?itemSearch='+itemSearchId+'&selecttype='+optVal;\r\n");
      out.write("		}\r\n");
      out.write("    	\r\n");
      out.write("    	function rowClicked() {\r\n");
      out.write("    		var opt = document.getElementById(\"searchselect\");\r\n");
      out.write("            var optVal = opt.options[opt.selectedIndex].value;\r\n");
      out.write("            \r\n");
      out.write("    		var table = document.getElementById('tableSelect');\r\n");
      out.write("    		var rowList = table.rows;\r\n");
      out.write("    		\r\n");
      out.write("    		for(i=1;i<rowList.length;i++){\r\n");
      out.write("    			var row = rowList[i];\r\n");
      out.write("    			\r\n");
      out.write("    			row.onclick = function () {\r\n");
      out.write("					return function () {\r\n");
      out.write("						if(optVal==\"item\"){\r\n");
      out.write("							var num = this.cells[0].innerHTML;\r\n");
      out.write("							var name =this.cells[2].innerHTML;\r\n");
      out.write("							var size = this.cells[3].innerHTML;\r\n");
      out.write("							\r\n");
      out.write("							document.getElementById('item_num').value=num;\r\n");
      out.write("							document.getElementById('item_num2').innerHTML=num;\r\n");
      out.write("							document.getElementById('item_name').value=name;\r\n");
      out.write("							document.getElementById('item_name2').innerHTML=name;\r\n");
      out.write("							document.getElementById('item_size').value=size;\r\n");
      out.write("							document.getElementById('item_size2').innerHTML=size;\r\n");
      out.write("						} else if(optVal==\"order\"){\r\n");
      out.write("							var num = this.cells[0].innerHTML;\r\n");
      out.write("							var name =this.cells[2].innerHTML;\r\n");
      out.write("							var size = this.cells[3].innerHTML;\r\n");
      out.write("							var quantity= this.cells[4].innerHTML;\r\n");
      out.write("							\r\n");
      out.write("							document.getElementById('item_num').value=num;\r\n");
      out.write("							document.getElementById('item_num2').innerHTML=num;\r\n");
      out.write("							document.getElementById('item_name').value=name;\r\n");
      out.write("							document.getElementById('item_name2').innerHTML=name;\r\n");
      out.write("							document.getElementById('item_size').value=size;\r\n");
      out.write("							document.getElementById('item_size2').innerHTML=size;\r\n");
      out.write("							\r\n");
      out.write("							document.getElementById('quantity').value=quantity;\r\n");
      out.write("						}\r\n");
      out.write("						\r\n");
      out.write("					};\r\n");
      out.write("				}(row);\r\n");
      out.write("    		}\r\n");
      out.write("		}\r\n");
      out.write("    	window.onload = rowClicked();\r\n");
      out.write("    	\r\n");
      out.write("    	function checkTest() {\r\n");
      out.write("    		if(!$('#item_date').val()){\r\n");
      out.write("    			alert('날짜를 입력하세요.');\r\n");
      out.write("    			$('#item_date').focus();\r\n");
      out.write("    			\r\n");
      out.write("    			return;\r\n");
      out.write("    		}\r\n");
      out.write("    		\r\n");
      out.write("    		if(!$('#quantity').val()){\r\n");
      out.write("    			alert('수량을 입력하세요.');\r\n");
      out.write("    			$('#quantity').focus();\r\n");
      out.write("    			\r\n");
      out.write("    			return;\r\n");
      out.write("    		}\r\n");
      out.write("    		if(!$('#item_num').val()){\r\n");
      out.write("    			alert('상품을 선택하세요.');\r\n");
      out.write("    			$('#item_num').focus();\r\n");
      out.write("    			\r\n");
      out.write("    			return;\r\n");
      out.write("    		}\r\n");
      out.write("    		document.getElementById('formInsert').submit();\r\n");
      out.write("		}\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
