/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-01-30 05:14:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1706489532000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/login.css\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Starbucks Korea Coffee</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"icon\" href=\"images/favicon.ico\">\r\n");
      out.write("    <script defer src=\"js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("    <script defer src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("    \r\n");
      out.write("    <!-- lodash -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js\"></script>\r\n");
      out.write("    <!-- gsap -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/gsap.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/ScrollToPlugin.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("    <!-- swiper 11버전 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper@6.8.4/swiper-bundle.min.css\">\r\n");
      out.write("    <script src=\"https://unpkg.com/swiper@6.8.4/swiper-bundle.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("        <div class=\"inner\">\r\n");
      out.write("            <a href=\"./index.jsp\" class=\"logo\">\r\n");
      out.write("                <img src=\"images/starbucks_logo.png\" alt=\"starbucks_logo\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"sub-menu\">\r\n");
      out.write("                <ul class=\"menu\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"login.jsp\">Sign In</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">My Starbucks</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">Customer Service & Ideas</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">Find a Store</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"search\">\r\n");
      out.write("                    <input type=\"text\">\r\n");
      out.write("                    <span class=\"material-symbols-outlined search-icon\">Search</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"main-menu\">\r\n");
      out.write("                <li class=\"item\">\r\n");
      out.write("                  <div class=\"item__name\">COFFEE</div>\r\n");
      out.write("                  <div class=\"item__contents\">\r\n");
      out.write("                    <div class=\"contents__menu\">\r\n");
      out.write("                      <ul class=\"inner\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <h4>커피</h4>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                            <li>스타벅스 원두</li>\r\n");
      out.write("                            <li>스타벅스 비아</li>\r\n");
      out.write("                            <li>스타벅스 오리가미</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <h4>에스프레소 음료</h4>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                            <li>도피오</li>\r\n");
      out.write("                            <li>에스프레소 마키아또</li>\r\n");
      out.write("                            <li>아메리카노</li>\r\n");
      out.write("                            <li>마키아또</li>\r\n");
      out.write("                            <li>카푸치노</li>\r\n");
      out.write("                            <li>라떼</li>\r\n");
      out.write("                            <li>모카</li>\r\n");
      out.write("                            <li>리스트레또 비안코</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <h4>커피 이야기</h4>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                            <li>스타벅스 로스트 스팩트럼</li>\r\n");
      out.write("                            <li>최상의 아라비카 원두</li>\r\n");
      out.write("                            <li>한 잔의 커피가 완성되기까지</li>\r\n");
      out.write("                            <li>클로버® 커피 추출 시스템</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <h4>최상의 커피를 즐기는 법</h4>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                            <li>커피 프레스</li>\r\n");
      out.write("                            <li>푸어 오버</li>\r\n");
      out.write("                            <li>아이스 푸어 오버</li>\r\n");
      out.write("                            <li>커피 메이커</li>\r\n");
      out.write("                            <li>리저브를 매장에서 다양하게 즐기는 법</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"contents__texture\">\r\n");
      out.write("                      <div class=\"inner\">\r\n");
      out.write("                        <h4>나와 어울리는 커피 찾기</h4>\r\n");
      out.write("                        <p>스타벅스가 여러분에게 어울리는 커피를 찾아드립니다.</p>\r\n");
      out.write("                        <h4>최상의 커피를 즐기는 법</h4>\r\n");
      out.write("                        <p>여러가지 방법을 통해 다양한 풍미의 커피를 즐겨보세요.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item\">\r\n");
      out.write("                  <div class=\"item__name\">MENU</div>\r\n");
      out.write("                  <div class=\"item__contents\">\r\n");
      out.write("                    <div class=\"contents__menu\">\r\n");
      out.write("                      <ul class=\"inner\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <h4>음료</h4>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                            <li>콜드 브루</li>\r\n");
      out.write("                            <li>브루드 커피</li>\r\n");
      out.write("                            <li>에스프레소</li>\r\n");
      out.write("                            <li>프라푸치노</li>\r\n");
      out.write("                            <li>블렌디드 음료</li>\r\n");
      out.write("                            <li>스타벅스 피지오</li>\r\n");
      out.write("                            <li>티(티바나)</li>\r\n");
      out.write("                            <li>기타 제조 음료</li>\r\n");
      out.write("                            <li>스타벅스 주스(병음료)</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <h4>푸드</h4>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                            <li>베이커리</li>\r\n");
      out.write("                            <li>케익</li>\r\n");
      out.write("                            <li>샌드위치 & 샐러드</li>\r\n");
      out.write("                            <li>따뜻한 푸드</li>\r\n");
      out.write("                            <li>과일 & 요거트</li>\r\n");
      out.write("                            <li>스낵 & 미니 디저트</li>\r\n");
      out.write("                            <li>아이스크림</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <h4>상품</h4>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                            <li>머그</li>\r\n");
      out.write("                            <li>글라스</li>\r\n");
      out.write("                            <li>플라스틱 텀블러</li>\r\n");
      out.write("                            <li>스테인리스 텀블러</li>\r\n");
      out.write("                            <li>보온병</li>\r\n");
      out.write("                            <li>액세서리</li>\r\n");
      out.write("                            <li>커피 용품</li>\r\n");
      out.write("                            <li>패키지 티(티바나)</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <h4>카드</h4>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                            <li>실물카드</li>\r\n");
      out.write("                            <li>e-Gift 카드</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <h4>메뉴 이야기</h4>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                            <li>콜드 브루</li>\r\n");
      out.write("                            <li>스타벅스 티바나</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"contents__texture\">\r\n");
      out.write("                      <div class=\"inner\">\r\n");
      out.write("                        <h4>스타벅스 티바나</h4>\r\n");
      out.write("                        <p>다양한 찻잎과 향신료 등 개성있는 재료로 새로운 맛과 향의 티를 선보입니다.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item\">\r\n");
      out.write("                  <div class=\"item__name\">STORE</div>\r\n");
      out.write("                  <div class=\"item__contents\">\r\n");
      out.write("                    <div class=\"contents__menu\">\r\n");
      out.write("                      <ul class=\"inner\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <h4>매장 찾기</h4>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                            <li>퀵 검색</li>\r\n");
      out.write("                            <li>지역 검색</li>\r\n");
      out.write("                            <li>My 매장</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <h4>매장 이야기</h4>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                            <li>청담스타</li>\r\n");
      out.write("                            <li>티바나 인스파이어드 매장</li>\r\n");
      out.write("                            <li>파미에파크</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"contents__texture\">\r\n");
      out.write("                      \r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item\">\r\n");
      out.write("                  <div class=\"item__name\">RESPONSIBILITY</div>\r\n");
      out.write("                  <div class=\"item__contents\">\r\n");
      out.write("                    <div class=\"contents__menu\">\r\n");
      out.write("        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"contents__texture\">\r\n");
      out.write("                      \r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item\">\r\n");
      out.write("                  <div class=\"item__name\">MY STARBUCKS REWARDS</div>\r\n");
      out.write("                  <div class=\"item__contents\">\r\n");
      out.write("                    <div class=\"contents__menu\">\r\n");
      out.write("        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"contents__texture\">\r\n");
      out.write("                      \r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item\">\r\n");
      out.write("                  <div class=\"item__name\">WHAT'S NEW</div>\r\n");
      out.write("                  <div class=\"item__contents\">\r\n");
      out.write("                    <div class=\"contents__menu\">\r\n");
      out.write("        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"contents__texture\">\r\n");
      out.write("                      \r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <div class=\"background\">\r\n");
      out.write("        <div class=\"size\">\r\n");
      out.write("                <div class=\"log\">로그인</div>\r\n");
      out.write("            <div class=\"loginbox\">\r\n");
      out.write("                    <div class=\"welcome\">Welcome! 스타벅스 코리아에 오신 것을 환영합니다.</div>\r\n");
      out.write("                        <form class=\"text\" action=\"loginSearch.jsp\" method=\"get\">\r\n");
      out.write("                        	<input type=\"text\" name=\"id\" class=\"lgtext\" id=\"\" placeholder=\"아이디를 입력해 주세요.\">\r\n");
      out.write("	                        <input type=\"password\" name=\"pw\"  class=\"lgtext\" id=\"\" placeholder=\"비밀번호를 입력해 주세요.\">\r\n");
      out.write("	                        <div class=\"check\">\r\n");
      out.write("	                            <input type=\"checkbox\" name=\"save\" id=\"save\">\r\n");
      out.write("	                            <label for=\"save\">아이디 저장</label>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <input type=\"submit\" value=\"로그인\" id=\"loginbtn\" onclick=\"\">\r\n");
      out.write("                        \r\n");
      out.write("                        <p>\r\n");
      out.write("                        * 타 사이트와 비밀번호를 동일하게 사용할 경우 도용의 위험이 있으므로, 정기적인 비밀번호 변경을 해주시길 바랍니다.\r\n");
      out.write("                        <br>\r\n");
      out.write("                        * 스타벅스 코리아의 공식 홈페이지는 Internet Explorer 9.0 이상, Chrome, Firefox, Safari 브라우저에 최적화 되어있습니다.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    	</form>\r\n");
      out.write("                        <div class=\"btn\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("                                <li><a href=\"#\">아이디 찾기</a></li>\r\n");
      out.write("                                <li><a href=\"#\">비밀번호 찾기</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    	\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
